//! The main page, `Project:Home` (`general.mainpage`): generated by the site until a page
//! of that title exists.
//!
//! The site has no document pages yet (0008; the pages stack comes in Phase 5), and an
//! adoption keeps only a dump's entity pages, so a dump's own main page is not carried
//! over. Once the API serves pages, a written `Project:Home` takes this one's place.

use std::fmt::Write as _;

use askama::Template as _;

use crate::codex::SearchInput;
use crate::features::Feature;
use crate::frame::Page;
use crate::html::{esc, link};
use crate::pages::Context;

/// The generated main page's body.
#[must_use]
pub fn body(cx: &Context) -> String {
    let m = &cx.m;
    let name = &cx.site.sitename;
    let mut s = format!(
        "<div class=\"ts-home\"><p class=\"ts-home__lead\">{}</p>",
        esc(&m.with("ts-home-lead", &[name]))
    );
    if cx.features.has(Feature::Search) {
        let _ = write!(
            s,
            "<form class=\"ts-home__search\" role=\"search\" aria-label=\"{}\" action=\"/w/index.php\" method=\"get\"><input type=\"hidden\" name=\"title\" value=\"Special:Search\">{}</form><p class=\"ts-home__hint\">{}</p>",
            esc(&m.with("ts-home-search-label", &[name])),
            SearchInput {
                name: "search",
                value: "",
                placeholder: &m.get("ts-search-placeholder"),
                label: &m.get("ts-search-label"),
                button: &m.get("ts-search-button"),
            }
            .render()
            .unwrap_or_default(),
            esc(&m.get("ts-home-hint"))
        );
    }
    let _ = write!(
        s,
        "<p class=\"ts-home__more\">{}</p><p class=\"ts-home__generated\">{}</p></div>",
        link(
            "/wiki/Special:SpecialPages",
            &esc(&m.get("ts-home-specialpages")),
            ""
        ),
        esc(&m.with("ts-home-generated", &[&cx.site.mainpage]))
    );
    s
}

/// The generated main page: the site's name as its heading, its own title in the
/// browser's.
#[must_use]
pub fn page(cx: &Context) -> Page {
    Page {
        title: cx.site.sitename.clone(),
        doc_title: Some(cx.site.mainpage.clone()),
        returnto: Some(cx.site.mainpage.clone()),
        body: body(cx),
        ..Page::default()
    }
}
