//! Which paths the site serves and which the API does (0057 §3): the one list the edge
//! proxy's configuration is printed from (`triplespace-web routes --format …`), and that
//! the embedded mode matches, since there the API's router answers these paths and the
//! site is its fallback.

use std::fmt::Write as _;

/// Who answers a path.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Target {
    /// The API (`triplespace-server`).
    Api,
    /// The site (`triplespace-web`, or the server's embedded site).
    Web,
}

/// How a path is matched.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Match {
    /// Exactly this path.
    Exact,
    /// This prefix and everything under it.
    Prefix,
}

/// One entry: a path, how it matches, who answers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Route {
    /// The path or prefix.
    pub path: &'static str,
    /// How it matches.
    pub how: Match,
    /// Who answers.
    pub target: Target,
}

const fn api(path: &'static str, how: Match) -> Route {
    Route {
        path,
        how,
        target: Target::Api,
    }
}

/// The API's paths. Everything else is the site's, which is the default route, so an
/// unknown path gets the site's 404 page in its frame. The media routes of 0039 §7 join
/// this list when they exist, where the media base shares the host.
pub const TABLE: &[Route] = &[
    api("/w/api.php", Match::Exact),
    api("/api.php", Match::Exact),
    api("/w/rest.php/", Match::Prefix),
    api("/rest.php/", Match::Prefix),
    api("/wiki/Special:EntityData/", Match::Prefix),
    api("/entity/", Match::Prefix),
    api("/.well-known/", Match::Prefix),
    api("/oauth/", Match::Prefix),
    api("/dumps/", Match::Prefix),
];

/// Who answers a path, by the longest match.
#[must_use]
pub fn target(path: &str) -> Target {
    TABLE
        .iter()
        .filter(|r| match r.how {
            Match::Exact => path == r.path,
            Match::Prefix => path.starts_with(r.path),
        })
        .max_by_key(|r| r.path.len())
        .map_or(Target::Web, |r| r.target)
}

/// The proxy configurations `routes` prints.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    /// A Caddyfile snippet.
    Caddy,
    /// nginx `location` blocks.
    Nginx,
    /// HAProxy frontend rules.
    Haproxy,
}

impl Format {
    /// From its name.
    #[must_use]
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "caddy" => Some(Self::Caddy),
            "nginx" => Some(Self::Nginx),
            "haproxy" => Some(Self::Haproxy),
            _ => None,
        }
    }
}

const HEADER: &str = "Generated by `triplespace-web routes` from the routing table of ADR 0057 §3. Regenerate rather than edit.";

/// Prints the table as proxy configuration.
#[must_use]
pub fn print(format: Format) -> String {
    match format {
        Format::Caddy => caddy(),
        Format::Nginx => nginx(),
        Format::Haproxy => haproxy(),
    }
}

fn caddy() -> String {
    let paths: Vec<String> = TABLE
        .iter()
        .map(|r| match r.how {
            Match::Exact => r.path.to_string(),
            Match::Prefix => format!("{}*", r.path),
        })
        .collect();
    format!(
        "# {HEADER}\n\
         # Import it into each tenant host's site block: `librarybase.org {{ import triplespace }}`.\n\
         # Set TRIPLESPACE_API and TRIPLESPACE_WEB to the upstreams. Caddy forwards Host and\n\
         # sets X-Forwarded-For itself; list its address in the server's --trusted-proxy, or\n\
         # give it a forwarder key with `header_up Triplespace-Forwarder {{$TRIPLESPACE_FORWARDER_KEY}}`.\n\
         (triplespace) {{\n\
         \t@triplespace_api path {}\n\
         \thandle @triplespace_api {{\n\
         \t\treverse_proxy {{$TRIPLESPACE_API}}\n\
         \t}}\n\
         \thandle {{\n\
         \t\treverse_proxy {{$TRIPLESPACE_WEB}}\n\
         \t}}\n\
         }}\n",
        paths.join(" ")
    )
}

fn nginx() -> String {
    let mut out = format!(
        "# {HEADER}\n\
         # Include it in each tenant host's server block. Define the upstreams triplespace_api\n\
         # and triplespace_web.\n"
    );
    let forward = "proxy_set_header Host $host; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme;";
    for r in TABLE {
        let loc = match r.how {
            Match::Exact => format!("= {}", r.path),
            Match::Prefix => format!("^~ {}", r.path),
        };
        let _ = writeln!(
            out,
            "location {loc} {{ proxy_pass http://triplespace_api; {forward} }}"
        );
    }
    let _ = writeln!(
        out,
        "location / {{ proxy_pass http://triplespace_web; {forward} }}"
    );
    out
}

fn haproxy() -> String {
    let exact: Vec<&str> = TABLE
        .iter()
        .filter(|r| r.how == Match::Exact)
        .map(|r| r.path)
        .collect();
    let prefix: Vec<&str> = TABLE
        .iter()
        .filter(|r| r.how == Match::Prefix)
        .map(|r| r.path)
        .collect();
    format!(
        "# {HEADER}\n\
         # Place these in the frontend; define the backends triplespace_api and triplespace_web.\n\
         \tacl triplespace_api path {}\n\
         \tacl triplespace_api path_beg {}\n\
         \tuse_backend triplespace_api if triplespace_api\n\
         \tdefault_backend triplespace_web\n",
        exact.join(" "),
        prefix.join(" ")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn longest_match_and_the_default() {
        assert_eq!(target("/w/api.php"), Target::Api);
        assert_eq!(target("/w/api.phpx"), Target::Web);
        assert_eq!(
            target("/w/rest.php/triplespace/v0/entity/Q6/provenance"),
            Target::Api
        );
        assert_eq!(target("/wiki/Special:EntityData/Q6.json"), Target::Api);
        assert_eq!(target("/wiki/Item:Q6"), Target::Web);
        assert_eq!(target("/wiki/Special:RecentChanges"), Target::Web);
        assert_eq!(target("/w/index.php"), Target::Web);
        assert_eq!(target("/"), Target::Web);
        assert_eq!(target("/ui/assets/site.css"), Target::Web);
    }

    #[test]
    fn every_format_names_every_path() {
        for f in [Format::Caddy, Format::Nginx, Format::Haproxy] {
            let text = print(f);
            for r in TABLE {
                assert!(text.contains(r.path), "{f:?} lacks {}", r.path);
            }
        }
        assert!(print(Format::Caddy).contains("/w/rest.php/*"));
        assert!(print(Format::Nginx).contains("location = /w/api.php"));
        assert!(print(Format::Nginx).contains("location ^~ /w/rest.php/"));
    }
}
